POST http://localhost:8080/query HTTP/1.1
content-type: application/json

{
    "query": "What is the capital of Germany?"
}



###


POST http://localhost:8080/query HTTP/1.1
content-type: application/json

{
    "query": "which involved rewriting the entire codebase?"
}
